[tox]
env_list =
    3.14.0
    3.13.0

minversion = 4.23.2

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=6
commands =
    pytest {tty:--color=yes} {posargs}
